//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizza_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CortesCaja
    {
        public int IdCorteCaja { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> Fondo { get; set; }
        public Nullable<double> IngresoRegistrados { get; set; }
        public Nullable<double> SalidasRegistradas { get; set; }
        public Nullable<double> TotalFinal { get; set; }
        public string NombreUsuario { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
