//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizza_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CortesCaja
    {
        public int IdCorteCaja { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<double> Fondo { get; set; }
        public Nullable<double> IngresoRegistrados { get; set; }
        public Nullable<double> SalidasRegistradas { get; set; }
        public Nullable<double> TotalFinal { get; set; }
        public string NombreUsuario { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
