//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizza_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insumos()
        {
            this.OrdenesCompraInsumos = new HashSet<OrdenesCompraInsumos>();
            this.RecetasInsumos = new HashSet<RecetasInsumos>();
        }
    
        public string CodigoProducto { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Costo { get; set; }
        public string Restricciones { get; set; }
        public Nullable<int> IdUnidadMedida { get; set; }
        public Nullable<int> IdCategoriaInsumo { get; set; }
    
        public virtual CategoriasInsumo CategoriasInsumo { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual UnidadesMedida UnidadesMedida { get; set; }
        public virtual InsumosApartados InsumosApartados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesCompraInsumos> OrdenesCompraInsumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecetasInsumos> RecetasInsumos { get; set; }
    }
}
