//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizza_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insumos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Insumos()
        {
            this.OrdenesCompraInsumos = new HashSet<OrdenesCompraInsumos>();
            this.RecetasInsumos = new HashSet<RecetasInsumos>();
        }
    
        public string CodigoProducto { get; set; }
        public Nullable<double> Cantidad { get; set; }
        public Nullable<double> Costo { get; set; }
        public string Restricciones { get; set; }
        public Nullable<int> IdUnidadMedida { get; set; }
        public Nullable<int> IdCategoriaInsumo { get; set; }
    
        public virtual CategoriasInsumo CategoriasInsumo { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual UnidadesMedida UnidadesMedida { get; set; }
        public virtual InsumosApartados InsumosApartados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesCompraInsumos> OrdenesCompraInsumos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecetasInsumos> RecetasInsumos { get; set; }
    }
}
