//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizza_DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ItaliaPizzaEntities : DbContext
    {
        public ItaliaPizzaEntities()
            : base("name=ItaliaPizzaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriasInsumo> CategoriasInsumo { get; set; }
        public virtual DbSet<CategoriasProductoVenta> CategoriasProductoVenta { get; set; }
        public virtual DbSet<CortesCaja> CortesCaja { get; set; }
        public virtual DbSet<Direcciones> Direcciones { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<EstadosOrdenCompra> EstadosOrdenCompra { get; set; }
        public virtual DbSet<EstadosPedido> EstadosPedido { get; set; }
        public virtual DbSet<GastosVarios> GastosVarios { get; set; }
        public virtual DbSet<Insumos> Insumos { get; set; }
        public virtual DbSet<InsumosApartados> InsumosApartados { get; set; }
        public virtual DbSet<OrdenesCompra> OrdenesCompra { get; set; }
        public virtual DbSet<OrdenesCompraInsumos> OrdenesCompraInsumos { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<PedidosProductosVenta> PedidosProductosVenta { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<ProductosVenta> ProductosVenta { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Recetas> Recetas { get; set; }
        public virtual DbSet<RecetasInsumos> RecetasInsumos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TiposEmpleado> TiposEmpleado { get; set; }
        public virtual DbSet<TiposServicio> TiposServicio { get; set; }
        public virtual DbSet<UnidadesMedida> UnidadesMedida { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<UsuariosPedidos> UsuariosPedidos { get; set; }
    }
}
