//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizza_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meseros
    {
        public int IdMesero { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string NombreUsuario { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
