//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizza_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesCompraInsumos
    {
        public int IdOrdenCompraInsumo { get; set; }
        public Nullable<int> CantidadInsumosAdquiridos { get; set; }
        public Nullable<int> IdOrdenCompra { get; set; }
        public string CodigoProducto { get; set; }
    
        public virtual Insumos Insumos { get; set; }
        public virtual OrdenesCompra OrdenesCompra { get; set; }
    }
}
