//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizza_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedidos()
        {
            this.PedidosProductosVenta = new HashSet<PedidosProductosVenta>();
            this.UsuariosPedidos = new HashSet<UsuariosPedidos>();
        }
    
        public int NumeroPedido { get; set; }
        public Nullable<System.DateTime> FechaPedido { get; set; }
        public Nullable<int> CantidadProductos { get; set; }
        public Nullable<double> TotalParaPagar { get; set; }
        public Nullable<int> IdEstadoPedido { get; set; }
        public Nullable<int> IdTipoServicio { get; set; }
    
        public virtual EstadosPedido EstadosPedido { get; set; }
        public virtual TiposServicio TiposServicio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosProductosVenta> PedidosProductosVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuariosPedidos> UsuariosPedidos { get; set; }
    }
}
