//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizza_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidosProductosVenta
    {
        public int IdPedidoProductoVenta { get; set; }
        public Nullable<int> NumeroPedido { get; set; }
        public string CodigoProducto { get; set; }
        public Nullable<int> CantidadProducto { get; set; }
    
        public virtual Pedidos Pedidos { get; set; }
        public virtual ProductosVenta ProductosVenta { get; set; }
    }
}
