//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizza_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosVenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductosVenta()
        {
            this.PedidosProductosVenta = new HashSet<PedidosProductosVenta>();
            this.Recetas = new HashSet<Recetas>();
        }
    
        public string CodigoProducto { get; set; }
        public Nullable<double> Precio { get; set; }
        public byte[] Foto { get; set; }
        public Nullable<int> IdCategoriaProductoVenta { get; set; }
    
        public virtual CategoriasProductoVenta CategoriasProductoVenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidosProductosVenta> PedidosProductosVenta { get; set; }
        public virtual Productos Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recetas> Recetas { get; set; }
    }
}
