//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItaliaPizza_DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public string CodigoProducto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> EsInventariado { get; set; }
        public Nullable<bool> EsActivo { get; set; }
    
        public virtual Insumos Insumos { get; set; }
        public virtual ProductosVenta ProductosVenta { get; set; }
    }
}
